# Generated by Django 4.0.3 on 2022-03-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='カテゴリー名')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('pic', models.ImageField(upload_to='', verbose_name='画像')),
                ('text', models.TextField(verbose_name='本文')),
                ('create_day', models.DateTimeField(auto_now_add=True)),
                ('update_day', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=True, verbose_name='非公開')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='タグ名')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
