# Generated by Django 4.0.3 on 2022-03-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='公開'),
        ),
    ]
