# Generated by Django 4.0.3 on 2022-03-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='blog_tags', to='blog.tag', verbose_name='タグ'),
        ),
    ]
